# -*- coding: utf-8 -*-
"""Capstone Project for AI Agents Intensive Course.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1moUPmqRHA1yrMBMkOzey3Ga1JSuCGphU

# CAPSTONE Project for AI Agents Intensive Course with Kaggle
## : Travel Concierge Multi-Agent System

*This notebook contains the  implementation of a Travel Concierge Multi-Agent System, developed as the capstone project for the 5-Day AI Agents Intensive Course with Google & Kaggle (2025).*

The system transforms a single natural-language travel request into:
1. Destination Research Summary
2. A realistic day-by-day travel itinerary
3. A full budget estimation (USD), computed using code execution

*All components are built using the Google Agent Development Kit (ADK) and the Gemini 2.5 Flash Lite model.*

### Problem Statement

The process of planning a trip is more than just choosing a destination and dividing the schedule.

Users typically have to repeat the following complex steps across multiple platforms; Navigating information from blogs, YouTube, and search engines...For travel beginners or those who lack time, it is time consuming, and they might lack of experience in configuring schedules. Sometimes the sources they research are too distracting and contain user-ads.

In other words, travel planning is a high-cost task that requires a lot of information collection, organization, inference, and calculation, and LLM-based automation is the most effective area to intervene.

The problem definition of this project is as follows.

"When a user enters the city, period, preference, and budget level,
Search for travel information → Create a schedule → Do budget calculations at once.

**"Can you provide an integrated travel planning automation system?"**

So if you can automate the three high-cost steps of "search → schedule → budget" into a single multi-agent, travel planning time can be reduced from hours to minutes, which means user satisfaction can also be greatly improved.

### Solution Overview

This project introduces the Travel Concierge Multi-Agent System, a fully automated travel-planning pipeline powered by Google’s Agent Development Kit (ADK).

The system transforms a single user request into:

1.   Destination Research Summary
2.   A realistic 3-day (or N-day) itinerary
3. A detailed, tool-assisted budget estimate (USD and local currency)


The solution is implemented using a three-agent pipeline:

**TravelResearchAgent**

- Uses Google Search to identify neighborhoods and recommended places
- Provides official website links and Google Maps URLs
- Outputs structured research notes

**ItineraryPlannerAgent**

- Reads research notes and user preferences
- Generates a realistic morning–afternoon–evening schedule per day
- Follows distance/pace constraints to keep itineraries feasible

**BudgetAgent**

- Extracts duration and activities from the itinerary
- Uses Built-in Python Code Execution for precise computation
- Produces a clean budget breakdown and assumptions


**TravelCoordinatorAgent (root agent)**

- Runs the full pipeline
- Ensures sequential execution (Research → Itinerary → Budget)
- Returns a single polished final output with three sections

The final product:
A structured, reliable travel plan generated end-to-end from one prompt.

### Architecture

Key Concepts Used

*   Multi-Agent System (Sequential orchestration)
*   LLM-powered Agents (Gemini 2.5 Flash Lite)
*   Built-in Tools (Google Search, Code Executor)
*   Session & State Management (InMemorySessionService)
*   Context Engineering (Explicit instruction templates and output keys)

### How to Run the Project
"""

pip install google-genai google-adk nest_asyncio requests

"""# Step 1 : Set API Key and retry settings"""

import os
from google.genai import types

os.environ["GOOGLE_API_KEY"] = "YOUR_KEY"   # <= Set Your API KEY here

# retry settings
retry_config = types.HttpRetryOptions(
    attempts=5,
    exp_base=7,
    initial_delay=1,
    http_status_codes=[429, 500, 503, 504],
)

print("Gemini API and retry settings ready.")

"""# Step 2: ADK fundamental components + Colab async environment preparation"""

import nest_asyncio
nest_asyncio.apply()  # prevent event loop collision when using async/await in Colab

from google.adk.agents import LlmAgent
from google.adk.models.google_llm import Gemini
from google.adk.runners import InMemoryRunner
from google.adk.sessions import InMemorySessionService

from google.adk.tools import google_search, ToolContext, AgentTool
from google.adk.tools.function_tool import FunctionTool
from google.adk.code_executors import BuiltInCodeExecutor

print("ADK core components imported.")

"""# Step 3: Define TravelResearchAgent"""

APP_NAME = "travel_app"

travel_research_agent = LlmAgent(
    name="TravelResearchAgent",
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    instruction=(
        "You are a travel research specialist.\n"
        "The user will tell you a city and some preferences.\n"
        "1) Use the google_search tool to find 3–7 interesting places in that city.\n"
        "2) Focus on places that match the user's preferences if provided "
        "(e.g., cafes, bookstores, museums, nature, restaurants).\n"
        "3) Return a concise, well-structured text summary that will be used by another agent "
        "to plan a day-by-day itinerary.\n"
        "Make sure your answer includes:\n"
        "- A short overview of the destination\n"
        "- A list of suggested neighborhoods/areas\n"
        "- A list of specific places with short reasons to visit\n"
    ),
    tools=[google_search],
    # IMPORTANT: store output in session state
    output_key="research_notes",
)

travel_research_runner = InMemoryRunner(
    app_name=APP_NAME,
    agent=travel_research_agent,
)

print("TravelResearchAgent Created")

"""# Step 4: Define ItineraryPlannerAgent"""

ITINERARY_SESSION_ID = "itinerary_session_1"

itinerary_agent = LlmAgent(
    name="ItineraryPlannerAgent",
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    instruction=(
        "You are a travel itinerary planner.\n"
        "You will receive:\n"
        "- The user's original request\n"
        "- Research notes about the destination in {research_notes}\n\n"
        "Using both, create a detailed day-by-day itinerary.\n\n"
        "Requirements:\n"
        "1) Plan exactly the requested number of days (e.g., 3 days).\n"
        "2) For each day, structure the plan with Morning / Afternoon / Evening.\n"
        "3) Use the places and neighborhoods from the research_notes where appropriate.\n"
        "4) Make the plan realistic in terms of distance and pace (do not schedule too many places).\n\n"
        "Output format (plain text):\n"
        "Day 1:\n"
        "  Morning: ...\n"
        "  Afternoon: ...\n"
        "  Evening: ...\n\n"
        "Day 2:\n"
        "  ...\n\n"
        "Day 3:\n"
        "  ...\n"
    ),
    # IMPORTANT: store itinerary in state for BudgetAgent
    output_key="itinerary_plan",
)

itinerary_runner = InMemoryRunner(
    app_name=APP_NAME,
    agent=itinerary_agent,
)

print("ItineraryPlannerAgent ready")

"""# Step 5: Define BudgetCalculatorAgent"""

budget_agent = LlmAgent(
    name="BudgetAgent",
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    instruction=(
        "You are a travel budget planner.\n"
        "You will receive an itinerary in {itinerary_plan} and the original user request.\n"
        "Your task is to automatically estimate the total budget without asking the user for numbers.\n"
        "Follow these rules:\n"
        "1) Infer the number of days from the itinerary (e.g., Day 1, Day 2, Day 3).\n"
        "2) For each day, calculate the following default costs (you may slightly adjust by city type):\n"
        "   - Local transport per day\n"
        "   - Meals per day\n"
        "   - Paid activities\n"
        "   - Cafe / snack\n"
        "3) Use the Built-in Code Executor to do the arithmetic. Do NOT do mental math; always rely on Python code.\n"
        "4) Estimate a reasonable flight ticket range based on the destination city, but keep it simple (e.g., 300–800 USD).\n\n"
        "Output structure (plain text):\n"
        "Total estimated budget: XXX–YYY USD\n\n"
        "Breakdown:\n"
        "- Flights: ...\n"
        "- Accommodation: ...\n"
        "- Food & drinks: ...\n"
        "- Local transport: ...\n"
        "- Activities & sightseeing: ...\n\n"
        "Assumptions:\n"
        "- List key assumptions you made (daily cost ranges, number of meals, etc.).\n"
        "Keep the explanation concise but clear."
    ),
    # Use the built-in Code Executor so the agent can call Python to compute totals
    code_executor=BuiltInCodeExecutor(),
    output_key="budget_summary",
)

budget_runner = InMemoryRunner(
    app_name=APP_NAME,
    agent=budget_agent,
)

print("BudgetAgent ready")

"""# Step 6: Define TravelCoordinatorAgent"""

# NOTE:
# - Replace `itinerary_agent` with the actual variable name of your itinerary planner agent.
# - Replace `budget_agent` with the actual variable name of your budget agent.

coordinator_agent = LlmAgent(
    name="TravelCoordinatorAgent",
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    instruction=(
    "You are a travel planning coordinator agent.\n"
    "Your job is to orchestrate three tools:\n"
    "1) TravelResearchAgent → produces research_notes\n"
    "2) ItineraryPlannerAgent → produces itinerary_plan\n"
    "3) BudgetAgent → produces budget_summary\n\n"
    "Workflow you MUST follow:\n"
    "Step 1: Call TravelResearchAgent using the user’s original message.\n"
    "Step 2: Call ItineraryPlannerAgent using both the user’s message and research_notes.\n"
    "Step 3: Call BudgetAgent using both the user’s message and itinerary_plan.\n\n"
    "When all results are ready, produce a clean, human-friendly answer that includes:\n"
    "  1) Destination Research Summary\n"
    "  2) Day-by-day Itinerary\n"
    "  3) Budget Estimate (with breakdown)\n"
    "Use clear section headings and bullet points.\n"
    ),
    tools=[
        AgentTool(travel_research_agent),
        AgentTool(itinerary_agent),
        AgentTool(budget_agent),
    ],
)

coordinator_runner = InMemoryRunner(
    app_name=APP_NAME,
    agent=coordinator_agent,
)

print("TravelCoordinatorAgent ready")

"""# Step 7: Agent/Runner Health Summary Check & Event/Session Status Dump Utility"""

def _safe(name, obj, attr, default=None):
    try:
        return getattr(obj, attr, default)
    except Exception:
        return default

print("=== Quick Summary ===")
try:
    print("[Research]  name:", _safe("r", travel_research_agent, "name"))
    print("[Research]  output_key:", _safe("r", travel_research_agent, "output_key"))
    print("[Itinerary] name:", _safe("i", itinerary_agent, "name"))
    print("[Itinerary] output_key:", _safe("i", itinerary_agent, "output_key"))
    print("[Budget]    name:", _safe("b", budget_agent, "name"))
    print("[Budget]    output_key:", _safe("b", budget_agent, "output_key"))
    print("[Coord]     name:", _safe("c", coordinator_agent, "name"))

    print("\n--- Runner app_name ---")
    print("research runner:", _safe("r", travel_research_runner, "app_name"))
    print("itinerary runner:", _safe("i", itinerary_runner, "app_name"))
    print("budget runner:", _safe("b", budget_runner, "app_name"))
    print("coordinator runner:", _safe("c", coordinator_runner, "app_name"))
except NameError as e:
    print("NameError:", e)

def dump_events(events):
    for i, ev in enumerate(events, 1):
        print(f"\n--- Event #{i} ---")
        role = getattr(getattr(ev, "content", None), "role", None)
        print(f"role: {role}  invocation_id: {getattr(ev, 'invocation_id', None)}")
        parts = getattr(getattr(ev, "content", None), "parts", None) or []
        for j, part in enumerate(parts, 1):
            if getattr(part, "text", None):
                print(f"  part[{j}] text:", part.text[:500])
            elif getattr(part, "function_call", None):
                fc = part.function_call
                print(f"  part[{j}] function_call name={fc.name} id={fc.id}")
            elif getattr(part, "function_response", None):
                fr = part.function_response
                print(f"  part[{j}] function_response name={fr.name} id={fr.id}")
                resp = getattr(fr, "response", {})
                print("    response keys:", list(resp.keys()))

async def dump_session_state(runner, app_name, user_id, session_id):
    sess = await runner.session_service.get_session(
        app_name=app_name, user_id=user_id, session_id=session_id
    )
    print("\n=== session.state keys ===")
    for k in sorted(sess.state.keys()):
        print(" -", k)
    print("\n== research_notes preview ==")
    print((sess.state.get("research_notes") or "")[:400])
    print("\n== itinerary_plan preview ==")
    print((sess.state.get("itinerary_plan") or "")[:400])
    print("\n== budget_summary preview ==")
    print((sess.state.get("budget_summary") or "")[:400])

"""# Step 8: New Session Smoke Test"""

import uuid

USER_ID = "test_user"
TRAVEL_SESSION_ID = f"smoke_{uuid.uuid4().hex[:6]}"

session = await coordinator_runner.session_service.create_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=TRAVEL_SESSION_ID
)
print("Session created:", session.id)

user_request = (
    "I want to visit Hong Kong for 3 days from Seoul. "
    "I prefer cafes, good food, shopping, and calm neighborhoods. "
    "Please plan the trip and estimate the budget in USD."
)

events = []
async for ev in coordinator_runner.run_async(
    user_id=USER_ID,
    session_id=TRAVEL_SESSION_ID,
    new_message=types.Content(role="user", parts=[types.Part(text=user_request)]),
):
    events.append(ev)

print("\n=== EVENTS ===")
dump_events(events)

await dump_session_state(
    runner=coordinator_runner,
    app_name=APP_NAME,
    user_id=USER_ID,
    session_id=TRAVEL_SESSION_ID
)

"""# Step 9: Final Output"""

sess = await coordinator_runner.session_service.get_session(
    app_name=APP_NAME, user_id=USER_ID, session_id=TRAVEL_SESSION_ID
)

pref = (sess.state.get("preference_summary") or "").strip()
research = (sess.state.get("research_notes") or "").strip()
itinerary = (sess.state.get("itinerary_plan") or "").strip()
budget = (sess.state.get("budget_summary") or "").strip()

print("\n===== Fallback composed answer =====\n")
if pref:
    print("Personalization Used\n--------------------")
    print(pref, "\n")
print("Destination Research Summary\n----------------------------")
print(research or "(no research_notes)", "\n")
print("Day-by-day Itinerary\n---------------------")
print(itinerary or "(no itinerary_plan)", "\n")
print("Budget Estimate\n---------------")
print(budget or "(no budget_summary)")

"""
***Credits***

*This project was created as part of the
Google × Kaggle – 5-Day AI Agents Intensive Course (2025).*

*Built by: Hyounjin Bae with help of ChatGPT 5.1*

*Powered by: Google ADK, Gemini 2.5, and Google Search Tool.*


"""
